services:
  postgres:
    container_name: opensociocracy-pg
    hostname: "postgres"
    command: ["postgres", "-c", "log_statement=all"]
    image: "postgres:14"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      timeout: 45s
      interval: 10s
      retries: 10
    ports:
      - "5432:5432"
    restart: always
    env_file: .env
    networks:
      - opensociocracy-net
    volumes:
      - opensociocracy-pg:/var/lib/postgres/data
      - ./postgres:/docker-entrypoint-initdb.d/

  api:
    container_name: opensociocracy-api
    image: opensociocracy/api
    restart: always
    build: ./api
    command: ["npm", "run", "dev"]
    # command: ["npm", "run", "dev:debug"]
    ports:
      - "3005:3005"
    env_file: ".env"
    networks:
      - opensociocracy-net
    volumes:
      - "./api/src/plugins:/usr/src/app/plugins"
      - "./api/src/routes:/usr/src/app/routes"
      - "./api/src/index.ts:/usr/src/app/index.ts"

  redis:
    image: redis:7.0.7
    container_name: opensociocracy-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - opensociocracy-net
    # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - opensociocracy-redis:/data

  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql:4.6
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 3567:3567
    container_name: opensociocracy-supertokens
    env_file: ".env"
    environment: 
      - POSTGRESQL_TABLE_SCHEMA=supertokens
    networks:
      - opensociocracy-net
    restart: always
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/0.0.0.0/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 0.0.0.0:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5

  smtp4dev:
    container_name: opensociocracy-smtp4dev
    image: rnwood/smtp4dev:v3
    restart: always
    env_file: .env
    networks:
      - opensociocracy-net
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'
    volumes:
      # This is where smtp4dev stores the database..
      - opensociocracy-smtp4dev:/smtp4dev

  gateway:
    image: ultri/open-platform-gateway:latest
    container_name: opensociocracy-gateway
    restart: always
    ports:
      - "80:80"
      - "443:443"
    env_file: ".env"
    networks:
      - opensociocracy-net
    volumes:
      - "./gateway/config/sites/prod/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
      - "./gateway/config/account.key:/etc/openresty/account.key"
      - "./gateway/certs/default.key:/etc/openresty/default.key"
      - "./gateway/certs/default.pem:/etc/openresty/default.pem"
      - "./gateway/html:/usr/local/openresty/nginx/html"
      - "./logs/gateway:/usr/local/openresty/nginx/logs"
    depends_on:
      - redis
      - supertokens
      - api
      - postgres

volumes:
  opensociocracy-smtp4dev: {}
  opensociocracy-pg: {}
  opensociocracy-redis: {}

networks:
  opensociocracy-net:
    external: false
    driver: bridge
