#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER"  --dbname "$DB_NAME" <<-EOSQL
  BEGIN;
    GRANT USAGE ON SCHEMA opensociocracy_api TO $API_USER;
    GRANT ALL ON ALL SEQUENCES IN SCHEMA opensociocracy_api TO $API_USER;
    GRANT ALL ON ALL TABLES IN SCHEMA opensociocracy_api TO $API_USER;
    GRANT ALL ON ALL FUNCTIONS IN SCHEMA opensociocracy_api TO $API_USER;
    ALTER ROLE $API_USER SET search_path = opensociocracy_api,public;

    GRANT USAGE ON SCHEMA supertokens TO $SUPERTOKENS_USER;
    GRANT ALL ON ALL SEQUENCES IN SCHEMA supertokens TO $SUPERTOKENS_USER;
    GRANT ALL ON ALL TABLES IN SCHEMA supertokens TO $SUPERTOKENS_USER;
    GRANT ALL ON ALL FUNCTIONS IN SCHEMA supertokens TO $SUPERTOKENS_USER;
    ALTER ROLE $SUPERTOKENS_USER SET search_path = supertokens,public;
    ALTER SCHEMA supertokens OWNER TO $SUPERTOKENS_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA supertokens GRANT ALL ON SEQUENCES TO $SUPERTOKENS_USER ;
    ALTER DEFAULT PRIVILEGES IN SCHEMA supertokens GRANT ALL ON TABLES TO $SUPERTOKENS_USER ;
    ALTER DEFAULT PRIVILEGES IN SCHEMA supertokens GRANT ALL ON FUNCTIONS TO $SUPERTOKENS_USER ;
    
  COMMIT;

EOSQL