#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER"  --dbname "$DB_NAME" <<-EOSQL
  BEGIN;
    CREATE USER $API_USER WITH PASSWORD '$API_PASS';
    GRANT CONNECT ON DATABASE $DB_NAME TO $API_USER;
    CREATE SCHEMA IF NOT EXISTS opensociocracy_api;
    GRANT USAGE ON SCHEMA opensociocracy_api TO $API_USER;
    GRANT ALL ON ALL SEQUENCES IN SCHEMA opensociocracy_api TO $API_USER;
    GRANT ALL ON ALL TABLES IN SCHEMA opensociocracy_api TO $API_USER;
    GRANT ALL ON ALL FUNCTIONS IN SCHEMA opensociocracy_api TO $API_USER;
    ALTER ROLE $API_USER SET search_path = opensociocracy_api,public;

    CREATE USER $SUPERTOKENS_USER WITH PASSWORD '$SUPERTOKENS_PASS';
    GRANT CONNECT ON DATABASE $DB_NAME TO $SUPERTOKENS_USER;
    CREATE SCHEMA IF NOT EXISTS supertokens;
    GRANT USAGE ON SCHEMA supertokens TO $SUPERTOKENS_USER;
    GRANT ALL ON ALL SEQUENCES IN SCHEMA supertokens TO $SUPERTOKENS_USER;
    GRANT ALL ON ALL TABLES IN SCHEMA supertokens TO $SUPERTOKENS_USER;
    GRANT ALL ON ALL FUNCTIONS IN SCHEMA supertokens TO $SUPERTOKENS_USER;
    ALTER ROLE $SUPERTOKENS_USER SET search_path = supertokens,public;
    ALTER SCHEMA supertokens OWNER TO $SUPERTOKENS_USER;
    
  COMMIT;

EOSQL